# Generated by Django 2.2.22 on 2021-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0002_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoFinanceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('origem', models.CharField(max_length=200)),
                ('data_movimento', models.DateField()),
            ],
        ),
    ]
