# Generated by Django 2.2.22 on 2021-05-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0004_origemmovimentofinanceiro_tipomovimentofinanceiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentofinanceiro',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igreja.TipoMovimentoFinanceiro'),
        ),
    ]
