# Generated by Django 2.2.22 on 2021-05-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0006_auto_20210515_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentofinanceiro',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
